name: Automated testing

# Currently we run in two situations:
on:
  # 1) Whenever someone pushes to a branch
  push:
  # 2) Whenever a pull request is opened, reopened or gets new commits.
  pull_request:
# This implies that for every push to a local branch in our repo for which a
# pull request is open this runs twice. But it's important to ensure that pull
# requests get tested even if their branch comes from a fork.

# Cancel running builds on push on the same branch or pull request
concurrency:
  group: "${{ github.workflow }}-${{ github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  test-on-iot-texlive:
    runs-on: ubuntu-22.04
    name: "Test suite Linux"
    container:
      image: registry.gitlab.com/islandoftex/images/texlive:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          show-progress: 'false'
      - name: Run l3build
        run: l3build check --show-log-on-error -q -H
      - name: Archive failed test output
        if: ${{ always() }}
        uses: zauguin/l3build-failure-artifacts@v1
        with:
          name: testfiles-${{ matrix.platform }}
          retention-days: 3

  doc-on-iot-texlive:
    runs-on: ubuntu-22.04
    name: Documentation
    container:
      image: registry.gitlab.com/islandoftex/images/texlive:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          show-progress: 'false'
      - name: Run l3build
        run: l3build doc -q -H
      - name: Archive documentation
        uses: actions/upload-artifact@v4
        with:
          name: Documentation
          path: "build/doc/*.pdf"
          retention-days: 21
